# Generated by Django 2.2.7 on 2019-12-03 09:20

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add you title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add your additional', required=True))])), ('full_rich_text', streams.blocks.RichTextBlock()), ('simple_rich_text', streams.blocks.SimpleRichTextBlock()), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(requied=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, requied=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_value1', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the buttton above selected, that will be used first.', required=False)), ('button_value2', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('button_page2', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url2', wagtail.core.blocks.URLBlock(help_text='If the buttton above selected, that will be used first.', required=False)), ('button_value3', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('button_page3', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url3', wagtail.core.blocks.URLBlock(help_text='If the buttton above selected, that will be used first.', required=False))])))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=40, required=True))]))], blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Flex Page',
                'verbose_name_plural': 'Flex Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
