# Generated by Django 2.2.7 on 2019-12-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='custom_title',
            field=models.CharField(help_text='Overwrites the default title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistpage',
            name='custom_title',
            field=models.CharField(help_text='Overwrites the default title', max_length=100),
        ),
    ]
